openapi: 3.0.3
info:
  title: Posts
  version: '2.0.0'
  contact: {}
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/TheHugz1997/ms_student/2.0.0
  - url: http://localhost
tags:
  - name: Posts
    description: Post in a thread
  - name: Categories
    description: Categories of a thread
  - name: Reactions
    description: Reactions to the posts
  - name: Tags
    description: Tags of the thread
  - name: Threads
    description: Thread management
paths:
  /posts/{postId}:
    get:
      tags:
        - Posts
      summary: Get specific post
      description: Get specific post
      operationId: getSpecificPost
      parameters:
        - in: path
          name: postId
          required: true
          description: ID of the post to get
          schema:
            type: string
      responses:
        '200':
          description: ''
        '400':
          description: Bad request
        '404':
          description: The post with the specified ID is not found
    patch:
      tags: 
        - Posts
      summary: Update post
      description: Update post
      operationId: updatePost
      parameters:
        - in: path
          name: postId
          required: true
          description: ID of the post to update
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                authorId:
                  type: string
                  example: d66b3f8c-2271-4afb-a348-e370ef9990
                content:
                  type: string
                  example: Update
            example:
              authorId: d66b3f8c-2271-4afb-a348-e370ef9990
              content: Update
      responses:
        '200':
          description: ''
        '400':
          description: Bad request
        '404':
          description: The post with the specified ID is not found
    delete:
      tags: 
        - Posts
      summary: Delete post
      description: Delete post
      operationId: deletePost
      parameters:
        - in: path
          name: postId
          required: true
          description: ID of the post to delete
          schema:
            type: string
      responses:
        '200':
          description: ''
        '400':
          description: Bad request
        '404':
          description: The post with the specified ID is not found
  /posts:
    get:
      tags: 
        - Posts
      summary: Get all posts
      description: Get all posts
      operationId: getAllPosts
      responses:
        '200':
          description: ''
        '400':
          description: Bad request
  /posts/{postId}/answers:
    put:
      tags: 
        - Posts
      summary: Reply to post
      description: Reply to post
      operationId: replyToPost
      parameters:
        - in: path
          name: postId
          required: true
          description: ID of the post to answer
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                authorId:
                  type: string
                  example: d66b3f8c-2271-4afb-a348-e370ef9990
                content:
                  type: string
                  example: Second child man
            example:
              authorId: d66b3f8c-2271-4afb-a348-e370ef9990
              content: Second child man
      responses:
        '200':
          description: ''
        '400':
          description: Bad request
        '404':
          description: The post with the specified ID is not found
  /categories:
    get:
      tags: 
        - Categories
      summary: Get all categories
      description: Get all categories
      operationId: getAllCategories
      responses:
        '200':
          description: ''
    post:
      tags: 
        - Categories
      summary: Create category
      description: Create category
      operationId: createCategory
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Electronic
            example:
              title: Electronic
      responses:
        '200':
          description: ''
        '400':
          description: Bad request
  /categories/{categoryId}:
    delete:
      tags: 
        - Categories
      summary: Delete category
      description: Delete category
      parameters:
        - in: path
          name: categoryId
          required: true
          description: ID of the category to delete
          schema:
            type: string
      operationId: deleteCategory
      responses:
        '200':
          description: ''
  /posts/{postId}/reactions:
    get:
      tags: 
        - Reactions
      summary: Get reaction for post
      description: Get reaction for post
      parameters:
        - in: path
          name: postId
          required: true
          description: ID of the post
          schema:
            type: string
      operationId: getReactionForPost
      responses:
        '200':
          description: ''
    put:
      tags: 
        - Reactions
      summary: Update reaction
      description: Update reaction
      parameters:
        - in: path
          name: postId
          required: true
          description: ID of the post to react to
          schema:
            type: string
      operationId: updateReaction
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                authorId:
                  type: string
                  example: d66b3f8c-2271-4afb-a348-e370ef9995
                value:
                  type: number
                  example: -1
            example:
              authorId: d66b3f8c-2271-4afb-a348-e370ef9995
              value: -1
      responses:
        '200':
          description: ''
        '400':
          description: Bad request
    delete:
      tags: 
        - Reactions
      summary: Delete reactions for post
      description: Delete reactions for post
      parameters:
        - in: path
          name: postId
          required: true
          description: ID of the post you want to delete the reaction
          schema:
            type: string
      operationId: deleteReactionsForPost
      responses:
        '200':
          description: ''
  /threads/{threadId}/tags:
    get:
      tags: 
        - Tags
      summary: Thread's tags
      description: Thread's tags
      parameters:
        - in: path
          name: threadId
          required: true
          description: ID of the thread you want to get the tags
          schema:
            type: string
      operationId: threadSTags
      responses:
        '200':
          description: ''
    post:
      tags: 
        - Tags
      summary: Tag to thread
      description: Tag to thread
      parameters:
        - in: path
          name: threadId
          required: true
          description: ID of the thread which you want to add a tag
          schema:
            type: string
      operationId: tagToThread
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tag :
                  type : string
                  example : mathématiques
            example:
              tag : mathématiques
      responses:
        '200':
          description: ''
        '400':
          description: Bad request
  /threads/{threadId}/tags/{tagtitle}:
    delete:
      tags: 
        - Tags
      summary: Delete tag
      description: Delete tag
      parameters: 
        - in : path
          name : threadId
          required: true
          description: Id of the thread which you want to delete the tag
          schema:
            type: string
        - in : path
          name : tagtitle
          required: true
          description: Id of the tag
          schema:
            type: string
      operationId: deleteTag
      responses:
        '200':
          description: ''
  /threads:
    get:
      tags: 
        - Threads
      summary: Threads list
      description: Threads list
      operationId: threadsList
      responses:
        '200':
          description: ''
    post:
      tags: 
        - Threads
      summary: Create thread
      description: Create thread
      operationId: createThread
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  example: Math
                firstPost:
                  type: object
                  properties:
                    authorId:
                      type: string
                      example: d66b3f8c-2271-4afb-a348-e370effff
                    content:
                      type: string
                      example: First post man
                tags:
                  type: array
                  items: {}
                  example: []
                title:
                  type: string
                  example: Test thread
            example:
              category: Math
              firstPost:
                authorId: d66b3f8c-2271-4afb-a348-e370effff
                content: First post man
              tags: []
              title: Test thread
      responses:
        '200':
          description: ''
        '400':
          description: Bad request
  /threads/{threadId}:
    patch:
      tags: 
        - Threads
      summary: Update thread
      description: Update thread
      parameters :
        - in : path
          name : threadId
          required : true
          description : Id of the thread you want to modify
          schema :
            type : string
      operationId: updateThread
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                answered:
                  type: boolean
                  example: true
                category:
                  type: string
                  example: Electronics
                title:
                  type: string
                  example: Updated thread
            example:
              answered: true
              category: Electronics
              title: Updated thread
      responses:
        '200':
          description: ''
    delete:
      tags: 
        - Threads
      summary: Delete thread
      description: Delete thread
      parameters :
        - in : path
          name : threadId
          required : true
          description : Id of the thread you want to delete
          schema :
            type : string
      operationId: deleteThread
      responses:
        '200':
          description: ''
    get:
      tags: 
        - Threads
      summary: Get specific thread
      description: Get specific thread
      parameters :
        - in : path
          name : threadId
          required : true
          description : Id of the thread you want to get
          schema :
            type : string
      operationId: getSpecificThread
      responses:
        '200':
          description: ''